<?php
// @codingStandardsIgnoreFile
/** @var \Verifone\Payment\Block\System\Config\Button\KeyGeneration $block */
?>
<script>
    require(['prototype'], function () {

        function generateKeysVerifone() {
            var validationMessage = $('generation-keys-result-verifone');

            params = {
                merchant_agreement_code: $$('input[id$="<?php /* @escapeNotVerified */ echo $block->getMerchantAgreementCodeField(); ?>"]').first().value,
                shop_private_keyfile: $$('input[id$="<?php /* @escapeNotVerified */ echo $block->getShopPrivateKeyfileField(); ?>"]').first().value,
                website: '<?php echo $block->getWebsiteId(); ?>'
            };

            new Ajax.Request('<?php /* @escapeNotVerified */ echo $block->getAjaxUrl() ?>', {
                parameters: params,
                onSuccess: function (response) {

                    var message = '<?php /* @escapeNotVerified */ echo __('Problem with generate new keys.') ?>';

                    try {
                        if (response.responseText.isJSON()) {

                            var result = response.responseText.evalJSON();
                            message = result.messages.join('<br/>');

                        }

                        if (result.valid === true) {
                            validationMessage.removeClassName('hidden').addClassName('success');
                        } else {
                            validationMessage.removeClassName('hidden').addClassName('error')
                        }
                    } catch (e) {
                        validationMessage.removeClassName('hidden').addClassName('error')
                    }

                    validationMessage.update(message);
                }
            });
        }

        function GenerateKeysVerifoneTrigger() {
            if (confirm('<?php echo $this->getConfirmationMessage(); ?>')) {
                generateKeysVerifone();
            } else {
                // Do nothing!
            }
        }

        window.GenerateKeysVerifoneTrigger = GenerateKeysVerifoneTrigger;

    });
</script>
<div class="actions actions-keys-generation-verifone">
    <div id="generation-keys-result-verifone" class="keys-message-validation hidden"></div>
    <button onclick="javascript:GenerateKeysVerifoneTrigger(); return false;" class="action-key-generation"
            type="button" id="<?php echo $block->getHtmlId() ?>">
        <span><?php echo $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
</div>
