<?php
// @codingStandardsIgnoreFile
/** @var \Verifone\Payment\Block\System\Config\Button\RefreshPayments $block */
?>
<script>
  require(['prototype'], function () {

    function refreshVerifonePayments() {
      var validationMessage = $('result');

      params = {
        merchant_agreement_code: $$('input[id$="<?php /* @escapeNotVerified */ echo $block->getMerchantAgreementCodeField(); ?>"]').first().value,
        merchant_agreement_code_test: $$('input[id$="<?php /* @escapeNotVerified */ echo $block->getMerchantAgreementCodeTest(); ?>"]').first().value,
        shop_private_keyfile: $$('input[id$="<?php /* @escapeNotVerified */ echo $block->getShopPrivateKeyfileField(); ?>"]').first().value,
        shop_private_keyfile_test: $$('input[id$="<?php /* @escapeNotVerified */ echo $block->getShopPrivateKeyfileTest(); ?>"]').first().value,
        pay_page_public_keyfile: $$('input[id$="<?php /* @escapeNotVerified */ echo $block->getPayPagePublicKeyfileField(); ?>"]').first().value,
        pay_page_public_keyfile_test: $$('input[id$="<?php /* @escapeNotVerified */ echo $block->getPayPagePublicKeyfileTest(); ?>"]').first().value,
        is_live_mode: $$('select[id$="<?php /* @escapeNotVerified */ echo $block->getisLiveMode(); ?>"]').first().value
      };

      new Ajax.Request('<?php /* @escapeNotVerified */ echo $block->getAjaxUrl() ?>', {
        parameters: params,
        onSuccess: function (response) {
          var result = '<?php /* @escapeNotVerified */ echo __('Problem with fetch payment methods.') ?>';
          try {
            if (response.responseText.isJSON()) {
              response = response.responseText.evalJSON();
              var message = response.message;
              var methods = response.methods;
            }
            if (response.valid == 1) {
              validationMessage.removeClassName('hidden').addClassName('success');
            } else {
              validationMessage.removeClassName('hidden').addClassName('error')
            }
          } catch (e) {
            validationMessage.removeClassName('hidden').addClassName('error')
          }
          validationMessage.update(message);
        }
      });
    }

    window.refreshVerifonePayments = refreshVerifonePayments;

  });
</script>
<div class="actions actions-refresh-ayments">
    <div id="result" class="message-validation hidden"></div>
    <button onclick="javascript:refreshVerifonePayments(); return false;" class="action-refresh-ayments" type="button" id="<?php echo $block->getHtmlId() ?>">
        <span><?php echo $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
</div>
