<script type="text/javascript">
    //<![CDATA[
    document.addEventListener("DOMContentLoaded", function(event) {
        // Your code to run since DOM is loaded and ready
//    });
//    document.observe('dom:loaded', function () {
        // Get the modal
        var modal = document.getElementById("<?php echo $this->getHtmlId() . '-modal' ?>");

        // Get the button that opens the modal
        var btn = document.getElementById("<?php echo $this->getHtmlId() ?>");

        // Get the <span> element that closes the modal
        var span = modal.getElementsByClassName("close")[0];

        // When the user clicks the button, open the modal
        btn.onclick = function () {
            modal.style.display = "block";
        };

        // When the user clicks on <span> (x), close the modal
        span.onclick = function () {
            modal.style.display = "none";
        };

        // When the user clicks anywhere outside of the modal, close it
        window.onclick = function (event) {
            if (event.target == modal) {
                modal.style.display = "none";
            }
        }
    });

    //]]>
</script>

<div id="<?php echo $this->getHtmlId() . '-modal' ?>" class="verifone_summary_modal">

    <!-- Modal content -->
    <div class="modal-content">
        <div class="modal-header">
            <span class="close">&times;</span>
            <h2><?php echo __('Configuration summary'); ?> - <?php echo $this->getWebsiteName(); ?></h2>
        </div>
        <div class="modal-body">

            <table class="verifone_summary" cellspacing="0">
                <tbody>
                <?php foreach ($this->getConfigurationDataForDisplay() as $data): ?>
                    <tr class="border-bottom">
                        <td class="summary-label"><?php echo $data['label']; ?></td>
                        <td class="summary-value">
                            <pre class="strong"><?php echo $data['value']; ?></pre>
                            <?php if (isset($data['desc'])): ?>
                                <p class="note">
                                    <span class="<?php echo isset($data['desc_class']) ? $data['desc_class'] : ''; ?>">
                                        <?php echo $data['desc']; ?>
                                    </span>
                                </p>
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <div class="modal-footer">
            <h3>&nbsp</h3>
        </div>
    </div>

</div>

<div class="actions actions-display-summary-verifone">
    <button class="action-display-summary-verifone" type="button" id="<?php echo $block->getHtmlId() ?>">
        <span id="verifone_summary_button"><?php echo $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
</div>
