<?php
$data = $this->getCreateData();
$action = $data['action'];
unset($data['action']);
?>

Redirecting to VerifonePayment.
<form action="<?php echo $action ?>" method="POST" id="verifone_form" name="verifone_form">
    <?php foreach ($data as $name => $value): ?>
        <input type="hidden" name="<?php echo $name; ?>" value="<?php echo $value; ?>"/>
    <?php endforeach; ?>
</form>
<script type="text/javascript">document.getElementById("verifone_form").submit();</script>